name: Build and publish release
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        arch: [armv7, armv8, x64]
        include:
          - arch: armv7
            tag: armeabi-v7a
          - arch: armv8
            tag: arm64-v8a
          - arch: x64
            tag: x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Adobe AIR SDK
        uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "51.2.2"
          accept-license: true

      - name: Install asconfigc
        run: |
          npm install --global asconfigc
          asconfigc --version

      - name: Restore keystore
        run: mkdir certs && echo "${{ secrets.CERT_BASE64 }}" | base64 --decode > certs/android_certificate.p12

      - name: Get versionLabel
        id: getv
        run: echo "label=$(awk -F'[<>]' '/<versionLabel>/{print $3}' src/ProTankiAndroid-app.xml)" >> $GITHUB_OUTPUT

      - name: Build ${{ matrix.arch }}
        run: |
          sed -i "s|<buildArchitectures>.*</buildArchitectures>|<buildArchitectures>${{ matrix.arch }}</buildArchitectures>|" src/ProTankiAndroid-app.xml
          asconfigc --verbose --sdk $AIR_HOME --air android --storepass ${{ secrets.CERT_PASS }}
          mv bin/protanki-android.apk bin/protanki-android-${{ steps.getv.outputs.label }}-${{ matrix.tag }}.apk
        timeout-minutes: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: protanki-android-${{ matrix.tag }}
          path: bin/*.apk

  release:
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all APKs
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.apk
